import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { styles } from "@/style";



export const metadata: Metadata = {
  title: "Amir Hamza",
  description: "Developer Amir Hamza's Portfolio Website, Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased relative h-full w-full flex`}
        data-new-gr-c-s-check-loaded="14.1258.0"
        data-gr-ext-installed=""
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
